### ISSUE TITLE
Add Initial OpMode for moving the robot drive train

### ISSUE THREAD

**Issue by bsneade** [FTC14691-MechanicalMafia/2024_25_InToTheDeep_14691#3]
This initial op mode should

1. Set up the monitors
2. Map to top hat
3. Set the direction for the motors
4. Wait for start
5. Check button state
6. Do appropriate movement for button state

**Comment by MisterSpk** [comment]
Also adding telemetry information

**Comment by Shadowwalker47** [comment]
Turns out we do not need to initialize the top hat
